/* PDF ink takes Pencil events at the window and stops them there, so v194 as reviewed never
   saw PDF strokes as writing: a deferred save and a sync could start mid-stroke. The app's
   own reading.js is served with a small inspection hook appended and cloud sync stubbed. */
const fs=require('fs'), http=require('http'),path=require('path');
let playwright;try{playwright=require('playwright');}catch(_){playwright=require('playwright-core');}const {chromium}=playwright,{PDFDocument}=require('pdf-lib');
const root=path.resolve(__dirname,'..');const assert=require('node:assert/strict');
const server=http.createServer((req,res)=>{let file=path.join(root,decodeURIComponent(req.url.split('?')[0]));fs.readFile(file,(e,data)=>{if(e){res.writeHead(404);res.end();return;}if(file.endsWith('reading.js')){data=data.toString().replace(/\}\)\(\);\s*$/,`window.__review={get:()=>({workspacePenDown,workspacePenAt,lastInputAt,persistSoonSince,pdfActive:pdfInkController.active(),writes:window.__writes}),schedule:()=>{syncCfg={};doSync=()=>window.__syncRuns.push({at:Date.now(),active:pdfInkController.active(),down:workspacePenDown});gdriveSync=()=>{};iCloudSync=()=>{};scheduleSync();}};\n})();`);}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.html')?'text/html':file.endsWith('.css')?'text/css':'application/octet-stream');res.end(data);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH ? {executablePath:process.env.CHROME_PATH} : {})});try{const page=await browser.newPage({viewport:{width:1180,height:820},hasTouch:true,serviceWorkers:'block'});await page.goto(`http://127.0.0.1:${server.address().port}/reading.html`);await page.waitForFunction(()=>document.body.classList.contains('library-ready'));const pdf=await PDFDocument.create();pdf.addPage([612,792]);await page.locator('#pdfFile').setInputFiles({name:'quiet.pdf',mimeType:'application/pdf',buffer:Buffer.from(await pdf.save())});await page.waitForFunction(()=>document.body.classList.contains('zen')&&!!document.querySelector('.pdf-page canvas')?.width);await page.locator('#zenAnnotate').click();await page.locator('#zenWrite').click();await page.waitForTimeout(1700);
await page.evaluate(()=>{window.__writes=[];window.__syncRuns=[];const orig=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='readingRoom.v1')window.__writes.push({at:Date.now(),active:window.__review.get().pdfActive});return orig.call(this,key,value);};});
const box=await page.locator('.pdf-page .pdf-sheet').first().boundingBox();const point={x:box.x+100,y:box.y+150};
const fire=async(type,dx=0,id=71)=>page.evaluate(({type,p,id})=>{const target=document.elementFromPoint(p.x,p.y);target.dispatchEvent(new PointerEvent(type,{bubbles:true,cancelable:true,pointerType:'pen',pointerId:id,isPrimary:true,button:0,buttons:type==='pointerup'?0:1,pressure:type==='pointerup'?0:.6,clientX:p.x,clientY:p.y}));return __review.get();},{type,p:{x:point.x+dx,y:point.y},id});
await fire('pointerdown');await fire('pointermove',60);await fire('pointerup',65);await page.waitForTimeout(200);const second=await fire('pointerdown',0,72);assert.equal(second.workspacePenDown,1,'a PDF Pencil stroke counts as writing');await fire('pointermove',90,72);await page.evaluate(()=>__review.schedule());await page.waitForTimeout(6200);const held=await page.evaluate(()=>({state:__review.get(),sync:__syncRuns}));assert.deepEqual(held.state.writes.filter(w=>w.active),[],'no library save while a PDF stroke is down');assert.deepEqual(held.sync,[],'no sync while a PDF stroke is down');await fire('pointerup',95,72);await page.waitForTimeout(1600);const after=await page.evaluate(()=>__review.get());assert.ok(after.writes.length>=1,'the strokes save once the Pencil rests');console.log('PASS PDF Pencil strokes hold saves and sync until the Pencil rests');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
